// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsumugi.Infrastructure.Persistence;

#nullable disable

namespace Tsumugi.Infrastructure.Migrations
{
    [DbContext(typeof(TsumugiDbContext))]
    [Migration("20260627232546_AddDisabilityCertificateAndFaceSheet")]
    partial class AddDisabilityCertificateAndFaceSheet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Tsumugi.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BenefitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ConsultationEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultationProviderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultationProviderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ConsultationStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardianRelationship")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HighCostBenefitApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MealProvisionApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyCostCap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentBurden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientGender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplyDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplyNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("SupportCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpperLimitManagementProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Validity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Validity");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Disabilities", "Tsumugi.Domain.Entities.Certificate.Disabilities#DisabilityCategories", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Intellectual")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Disability_Intellectual");

                            b1.Property<bool>("Intractable")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Disability_Intractable");

                            b1.Property<bool>("Mental")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Disability_Mental");

                            b1.Property<bool>("Physical")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Disability_Physical");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractedSupplyDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Period");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.ContractedProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ContractDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractedSupplyDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("ContractedProviders", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.DailyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attendance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MealProvided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.HasIndex("RecipientId", "ServiceDate");

                    b.ToTable("DailyRecords", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.DisabilityCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextRenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("DisabilityCertificates", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.FaceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cohabitants")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentConditions")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyComposition")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LifeHistory")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Medications")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PensionDetails")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalWishes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDoctorHospital")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDoctorName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDoctorPhone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReceivesDisabilityPension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceivesNursingInsurance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportNeeds")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("FaceSheets", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionGrade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OfficeNumber")
                        .IsUnique();

                    b.ToTable("Offices", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.OfficeCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FlagsJson");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Period");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("OfficeCapabilities", (string)null);
                });

            modelBuilder.Entity("Tsumugi.Domain.Entities.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("KanaName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("KanjiName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.ToTable("Recipients", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
